### ISSUE TITLE
I try to submit my favorite Food but not storing the values. :)

### ISSUE THREAD

**Issue by tekcomp** [charleaux/angular-drag-and-drop-between-formarray#1]
![image](https://user-images.githubusercontent.com/1616316/59447112-c20f3000-8dd0-11e9-8bbe-7ed55492207c.png)

**Comment by charleaux** [comment]
it should be good now. take a look and let me know

**Comment by charleaux** [comment]
https://stackblitz.com/edit/angular-wtucqj
